// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGIds
{
        public const string achievement_il_y_a_un_dbut__tout = "CggI4pyy0DgQAhAA"; // <GPGSID>
        public const string achievement_toujours_l = "CggI4pyy0DgQAhAH"; // <GPGSID>
        public const string achievement_laissezmoi_consulter_mon_grimoire = "CggI4pyy0DgQAhAG"; // <GPGSID>
        public const string achievement_premiers_pas = "CggI4pyy0DgQAhAB"; // <GPGSID>
        public const string achievement_toujours_plus_loin = "CggI4pyy0DgQAhAF"; // <GPGSID>
        public const string achievement_la_onzime_fois_sera_la_bonne = "CggI4pyy0DgQAhAC"; // <GPGSID>
        public const string achievement_le_dbut_dune_grande_aventure = "CggI4pyy0DgQAhAE"; // <GPGSID>
        public const string achievement_une_page_se_tourne = "CggI4pyy0DgQAhAD"; // <GPGSID>
        public const string achievement_un_grand_merci_de_lquipe = "CggI4pyy0DgQAhAI"; // <GPGSID>
        public const string achievement_en_estu_bien_certain = "CggI4pyy0DgQAhAJ"; // <GPGSID>

}

